[project]
name = "shared"
version = "1.0.0"
description = "Shared packages"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.12.5",
]

[tool.uv.sources]
shared = { workspace = true }

[tool.setuptools.packages.find]
include = ["lib", "models"]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"
